### ISSUE TITLE
Updating spawn with a bed doesn't work

### ISSUE THREAD

**Issue by xAlicatt** [GStefanowich/MC-Server-Protection#1]
So when sleeping in a bed, and then clicking the thing in chat to update someone's spawn point, upon death they do not spawn in the new spawnpoint. They get sent to  the old one instead. We have attempted doing this multiple times with the same result.

**Comment by GStefanowich** [comment]
Just got reports of this today as well from users on my own server. I'll investigate into fixing it for the next release. Thanks for the report

**Comment by GStefanowich** [comment]
Fixed in 4f055e10946f240a8de47cb1e9e1351fdeefbe13, now available in [Version 1.1.0](https://github.com/GStefanowich/MC-Server-Protection/releases/tag/v1.1.0)
If you're using chunk protection, please make sure to read the changes for 1.1.0, as SQL is no longer the storage method for chunk protection. More info in the [updating guide](https://www.curseforge.com/minecraft/mc-mods/sewing-machine-utilities/pages/index/updating)
