### ISSUE TITLE
Server crashes upon entering the nether

### ISSUE THREAD

**Issue by Addermg** [GStefanowich/MC-Server-Protection#10]
I'm using the mod on a smp server with a couple of friends. We entered have gone to the nether before and everything was fine, but recently one of my friends was being attacked by some ghasts and had to rush to the portal. He got back home safely, but upon reentering the nether the whole server crashed. It seems from the crash report that the bug is caused by the mod trying to avoid the ghast's griefing to the portal on the overworld. Now the player mentioned before can't connect to the server without causing it to crash and any other players walking into the portal end up in the same situation. Resetting the nether dimension fixes the issue but the bug can probably occur again.
[crash-2020-03-25_10.10.28-server.txt](https://github.com/GStefanowich/MC-Server-Protection/files/4380307/crash-2020-03-25_10.10.28-server.txt)

**Comment by GStefanowich** [comment]
I can't seem to duplicate the crash, but I know what's causing the issue.

\-\-
In Vanilla Minecraft (for whatever reason) when fireballs explode they do so without providing a source of the explosion, they kind of just say "Cause an explosion here!" rather than "A fireball exploded, cause an explosion here". I created a patch for this, but one of your other mods may be overwriting it.

I've gone ahead and changed my patch so that it should still work without being erased, as well as changed some things so that a null entity won't cause a crash.
\-\-

An update will be out soon. I've been working on implementing some requested features, as well as some fun things for my own server.

Thanks for reporting this.
Cheers
