### ISSUE TITLE
[Suggestion/Maybe Bug?] Make shop chests not openable by other players

### ISSUE THREAD

**Issue by ZombieNW** [GStefanowich/MC-Server-Protection#27]
Im not too sure if this is supposed to happen and just isnt,
but when i make a shop chest, other players (non-ops) are able to open it.
Could this perhaps be added?

but for right now ill probably use HeyThatsMine to lock the chest that has it.

**Comment by ZombieNW** [comment]
also sorry I keep annoying you today lol

**Comment by GStefanowich** [comment]
Chests that are linked to a shop should be locked as part of the mod. If you're using another mod that also supports locking there may be a conflict.

Can you let me know if you're using chunk claims from my mod, and if you are, if all players are able to open chests belonging to another players claim?

Opening chests that are part of a claim, and opening chests that are part of a shop use the same block interaction code.

If you aren't using claims, and have "claims.enabled" set to false in the config, then I need to patch that, as disabling protection also disables shop chest locking.

> also sorry I keep annoying you today lol

No worries, I'm happy to get any reports of bugs so that I can get them fixed

**Comment by ZombieNW** [comment]
I have claims disabled, I made a shop and then de-oped one of my admins and had them try to open the chest and they could.
The shop chest was... complete, idk the right word for it but it had the colored text and was in stock.
So yes claims are OFF, and the de-oped person was able to open it.
Thank you

**Comment by GStefanowich** [comment]
> I have claims disabled

Claims being disabled is the cause of this behavior, I'll have to write in handling of locking chests another time. But thank you for reporting this

**Comment by ZombieNW** [comment]
So what should I do right now, is there a way to like soft lock claims?
Like enable claims but make sure nobody can claim anything? By changing the price or some variable?
Or just wait

**Comment by GStefanowich** [comment]
I investigated my code to see if you could set claims to "true" and set the chunk limit to "0", however that conflicts with the mods idea that having no limit isn't "unlimited" rather than "none".

While doing this investigation I just decided that altering the code to perform the locking with claims disabled should be pretty easy, and have [created another release](https://github.com/GStefanowich/MC-Server-Protection/releases/tag/v1.3.2). This should fix the problem.

If it does, let me know, or self close the issue if you can.

**Comment by ZombieNW** [comment]
Alright it worked thank you
