### ISSUE TITLE
Chat Formatting

### ISSUE THREAD

**Issue by ZombieNW** [GStefanowich/MC-Server-Protection#28]
Man it sure is fun leaving bug reports innit.

So my chat config is as follows
`"chat": {
    "modify": true,
    "show_towns": false,
    "format": "<%n> %m",
    "mute": {
      "personal_mute": true,
      "moderator_mute": true
    }
  },`

However
Chat messages still look like this
![image](https://user-images.githubusercontent.com/59242209/115476490-d3a89680-a1f6-11eb-8959-c409c700026e.png)
I changed the config THEN restarted, and it still appears like that.
As well, I only enabled chat because if i disabled it, it only disabled for chat, and not things like /msg or /mainhand,chest, etc

**Comment by GStefanowich** [comment]
Thanks for reporting things as you're coming across them.

Chat formatting is one of the config options that has not yet been implemented. It was a new option for the 1.16 update, which was requested in 1.15. I've added this issue to [the release notes](https://github.com/GStefanowich/MC-Server-Protection/releases/tag/v1.3.0) that it's not yet implemented (along with the other two)

I will however, have to change the other commands to use vanillas formatting if "modify" is set to `false`, as you've pointed out

**Comment by GStefanowich** [comment]
Just to follow up on this, as of [SewingMachine 1.3.3](https://github.com/GStefanowich/MC-Server-Protection/releases/tag/v1.3.3) setting `chat.modify` to `false` will now cause `/mainhand`, `/chest`, `/shrug`, `/tableflip`, so on and so forth to use Vanillas formatting.

Customizing the `chat.format` is still being worked on, due to potential formatting complexity. Looking to add new hexadecimal color support, hover text, etc. Chat formatting has become exponentially more complex in later minecraft versions

**Comment by GStefanowich** [comment]
Closing this issue now that as of [Sewing Machine 1.5.0](https://github.com/GStefanowich/MC-Server-Protection/releases/tag/v1.5.0) chat [formatting has been added](https://www.curseforge.com/minecraft/mc-mods/sewing-machine-utilities/pages/config/formatting).

Removing the mod conflicts with other chat mods is now the next step (#37 )
