### ISSUE TITLE
Cannot join the world with the mod

### ISSUE THREAD

**Issue by poseidoncarrot** [GStefanowich/MC-Server-Protection#61]
I added this mod onto my server and for some reason, it wouldn't allow me to join the server with a constant connection lost message.
Edit: This was done through aternos with "Sewing Machine 1.5.2 for 1.18.2"
![e211afef-7174-4d42-8a1e-6ed63fc907a3](https://user-images.githubusercontent.com/105404350/168486480-3a898248-4ee3-425d-aaca-a5a6903fae23.png)

**Comment by GStefanowich** [comment]
Due to the way that `Minecraft` handles Registries, if you have any mod on the *Client* that adds custom `Items`, `Blocks`, `Mobs`, etc. a Registry-Sync is run by Fabric that gets all registry entries from the *Server*. This includes Sewing-Machine, which is normally only server-side.

Installing the mod on the client-side will fix this issue.

**Comment by GStefanowich** [comment]
I wish that this were something I could fix myself, but it's handled by `Fabric API`, and making my mod incompatible with `Fabric API` would be foolish.

**Comment by poseidoncarrot** [comment]
How can I fix it? Do I just have to make clients download it?

**Comment by GStefanowich** [comment]
> Do I just have to make clients download it?

Unfortunately yes.

Hopefully Fabric API will introduce a solution in the future, but it's not anything high priority.
