### ISSUE TITLE
Admin Shop/Guide Book?

### ISSUE THREAD

**Issue by poseidoncarrot** [GStefanowich/MC-Server-Protection#62]
I don't seem to be able to sell or buy infinite items with the admin shop. The description said that admins can make infinite buy/sell shops but I can't find the command for that. Is there also a guidebook for the mod?

**Comment by GStefanowich** [comment]
I plan on moving the information over to a GitHub wiki in the future, but currently the information lives on Curse. ([Shop Signs](https://www.curseforge.com/minecraft/mc-mods/sewing-machine-utilities/pages/shop-signs) / [Admin Signs](https://www.curseforge.com/minecraft/mc-mods/sewing-machine-utilities/pages/shop-signs/admin-signs)).

Infinity-shops don't have any permission necessary to make them, you just have to be in Creative Mode (Since in Creative you have infinite items anyway, an infinity-item shop isn't much different).

> If you are a server admin and want to create an infinitely supplied sign you must A) Be in creative mode, B) Write "server" on the fourth line of the sign. Otherwise anything written on the last line is replaced with the shop keepers name.

Just make a normal shop sign like so

> [BUY]
> 32 sand
> 100
> **server**

Normally the 4th line of the sign fills in the players name, but by being in creative mode and signing "Server" it makes it into an infinite sign.

**Comment by poseidoncarrot** [comment]
oh ok, thanks

**Comment by poseidoncarrot** [comment]
Oh wait, sorry to bug you again but how do you make player towns? Since I know how to claim chunks but the player town doesn't seem to have a command

**Comment by GStefanowich** [comment]
There's a `/town` command for everything Towns related. You can look at the [command code if you want](https://github.com/GStefanowich/MC-Server-Protection/blob/4ad23835363b5627d5d547e9a797371434aad728/src/main/java/net/theelm/sewingmachine/commands/ClaimCommand.java#L305-L311). **Tldr;** though, the command is `/town new "My Cool Town"`

They're not very well documented because it's a system that I plan on heavily overhauling in the future. I'm trying to figure out the best way to make connected regions while not degrading performance any, and modding is just a hobby.

Right now making a town just makes all of the Mayors 'Personal chunks' into 'Town chunks' *(Which can then be given to other players manually with the `/town claim PlayerName` command)*. In the future Towns' chunks will all have to be connected in order to make up that specific Town.

The `Shop Signs` to sell chunks also still needs to be implemented, otherwise it's all just manual work from the Mayor.

**Comment by poseidoncarrot** [comment]
Thank you so much for the information, last time. I installed the mod a few days ago but uninstalled it for some other reasons. I want to reinstall it now but it keeps crashing for some reason. The crash log is https://mclo.gs/kXOKqwv and the mods I have are https://mclo.gs/FZRQLQ1 
This is in Aternos by the way.

**Comment by GStefanowich** [comment]
The crash log looks like a conflict with `htm 1.1.4`, which I assume is [Hey That's Mine](https://www.curseforge.com/minecraft/mc-mods/htm)?

The crash report says that it's a conflict with the [Ender Dragon](https://github.com/QuiltServerTools/HeyThatsMine/blob/88993033468b89cb8f07e9c8fb20608407da0709/src/main/java/com/github/fabricservertools/htm/mixin/events/EnderDragonEntityMixin.java) since both mods are using the same method of preventing the Dragon from breaking claimed blocks.

**Comment by poseidoncarrot** [comment]
ohhhhhh, I honestly totally forgot about that mod since I added that while trying to refind this one. Thank you so much for all the answer.
